# Generated by Django 5.0.4 on 2024-07-15 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domimo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_apartments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
