# Generated by Django 5.0.4 on 2024-07-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domimo", "0002_apartment_favorites_alter_apartment_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="number",
            field=models.IntegerField(),
        ),
    ]
